#ifndef HERMIT_CORE_WIN32_HPP
#define HERMIT_CORE_WIN32_HPP

typedef HANDLE HAMSICONTEXT;
typedef HANDLE HAMSISESSION;

typedef enum {
  AMSI_RESULT_CLEAN,
  AMSI_RESULT_NOT_DETECTED,
  AMSI_RESULT_BLOCKED_BY_ADMIN_START,
  AMSI_RESULT_BLOCKED_BY_ADMIN_END,
  AMSI_RESULT_DETECTED
} AMSI_RESULT;

#endif // HERMIT_CORE_WIN32_HPP