#ifndef HERMIT_CORE_MODULES_HPP
#define HERMIT_CORE_MODULES_HPP

#include "core/procs.hpp"

#include <windows.h>
#include <ntstatus.h>

// Generated by script/calc_hash_module
#define HASH_MODULE_KERNEL32    0xf4796887
#define HASH_MODULE_NTDLL       0x3cd7873f
#define HASH_MODULE_USER32      0xecf87bd5

namespace Modules
{
    ULONG StringToHashModule(WCHAR* wStr, SIZE_T dwStrLen);
    PVOID GetModuleByHash(DWORD dwHash);
    PVOID LoadModule(Procs::LPPROC_LDRLOADDLL lpLdrLoadDll, LPWSTR lpDllName);
}


#endif // HERMIT_CORE_MODULES_HPP