#ifndef HERMIT_CORE_PROCS_HPP
#define HERMIT_CORE_PROCS_HPP

#include "core/macros.hpp"
#include "core/nt.hpp"

#include <windows.h>

#define HASH_IV     0x35
#define RANDOM_ADDR 0xab10f29f

// Generated by script/calc_hash_module
#define HASH_MODULE_KERNEL32              0xf4796887
#define HASH_MODULE_NTDLL                 0x3cd7873f
#define HASH_MODULE_USER32                0xecf87bd5
// Generated by script/calc_hash_func.py
#define HASH_FUNC_NTFLUSHINSTRUCTIONCACHE 0x3a43951d
#define HASH_FUNC_DLLMAIN                 0xe2e2f348
#define HASH_FUNC_GETPROCADDRESS          0xafa3e09d
#define HASH_FUNC_LOADLIBRARYA            0x7069f241
#define HASH_FUNC_LOADLIBRARYW            0x7069f257
#define HASH_FUNC_MESSAGEBOXA             0xcc4a1d08
#define HASH_FUNC_MESSAGEBOXW             0xcc4a1d1e
#define HASH_FUNC_VIRTUALALLOC            0x5ae0dabf
#define HASH_FUNC_VIRTUALPROTECT          0x927857d9

namespace Procs
{
    // NTAPI
    typedef DWORD   (NTAPI* LPPROC_NTFLUSHINSTRUCTIONCACHE)(HANDLE ProcessHandle, PVOID BaseAddress, SIZE_T Length);
    // WINAPI
    typedef BOOL    (WINAPI* LPPROC_DLLMAIN)(HINSTANCE, DWORD, LPVOID);
    typedef HMODULE (WINAPI* LPPROC_LOADLIBRARYA)(LPCSTR lpLibFileName);
    typedef FARPROC (WINAPI* LPPROC_GETPROCADDRESS)(HMODULE hModule, LPCSTR lpProcName);
    typedef int     (WINAPI* LPPROC_MESSAGEBOXA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
    typedef int     (WINAPI* LPPROC_MESSAGEBOXW)(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType);
    typedef LPVOID  (WINAPI* LPPROC_VIRTUALALLOC)(LPVOID lpAddress, SIZE_T dwSize, DWORD flAllocationType, DWORD flProtect);
    typedef BOOL    (WINAPI* LPPROC_VIRTUALPROTECT)(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, PDWORD lpflOldProtect);
    typedef UINT    (WINAPI* LPPROC_WINEXEC)(LPCSTR lpCmdLine, UINT uCmdShow);

    ULONG StringToHashModule(WCHAR* wStr, SIZE_T dwStrLen);
    DWORD StringToHashFunc(char* str);
    PVOID GetModuleByHash(DWORD dwHash);
    PVOID GetProcAddressByHash(HMODULE hModule, DWORD dwHash);
}


#endif // HERMIT_CORE_PROCS_HPP